services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=R00Tpostgres
      - POSTGRES_DB=ss3fm
    volumes:
      - ./postgres:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=R00Tpostgres
      - KC_FEATURES=preview
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=R00Tkeycloak
    command: start-dev
  hasura:
    image: hasura/graphql-engine:v2.41.0.cli-migrations-v3
    depends_on:
      - postgres
      - keycloak
    restart: always
    healthcheck:
      disable: true
    ports:
      - 5000:8080
    environment:
      - HASURA_GRAPHQL_PG_DATABASE_URL=postgres://postgres:R00Tpostgres@postgres:5432/ss3fm
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://postgres:R00Tpostgres@postgres:5432/ss3fm
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=R00Thasura
      - HASURA_GRAPHQL_AUTH_HOOK=http://host.docker.internal:3000/auth
      - HASURA_ACTION_BASE_URL=http://host.docker.internal:3000/action
    volumes:
      - ./hasura/metadata:/hasura-metadata
    extra_hosts:
      - host.docker.internal:host-gateway
