services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=R00Tpostgres
      - POSTGRES_DB=ss3fm
    volumes:
      - ./postgres:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=R00Tpostgres
      - KC_FEATURES=preview
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=R00Tkeycloak
    command: start-dev